name: FTP Deploy to cPanel

on:
  push:
    branches:
    - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up FTP deploy
      run: |
        sudo apt-get install -y lftp

    - name: Deploy HTML files via FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_TARGET_DIR: "/public_html/mda"  # Adjust as needed based on your actual directory
      run: |
        lftp -f "
        open ftp://$FTP_SERVER
        user $FTP_USERNAME $FTP_PASSWORD
        cd $FTP_TARGET_DIR  # Navigate to your subdomain folder
        mirror -R ./  # Upload all files in the repository to the FTP server
        quit
        "
