name: FTP Deploy to cPanel

on:
  push:
    branches:
    - main  # or the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up FTP deploy
      run: |
        sudo apt-get install -y lftp

    - name: Deploy Laravel app via FTP
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_TARGET_DIR: "/public_html/mda/"  # Correct path for your subdomain directory
      run: |
        lftp -f "
        open ftp://$FTP_SERVER
        user $FTP_USERNAME $FTP_PASSWORD
        mirror -R ./ $FTP_TARGET_DIR/  # Ensure trailing slash for proper directory mirroring
        quit
        "
