name: Deploy HTML to Server

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install FTP deployment tool (lftp)
    - name: Install lftp
      run: sudo apt-get install -y lftp

    # Step 3: List files in the working directory to verify the path
    - name: List files in the working directory
      run: |
        ls -l ./public_html

    # Step 4: Deploy the HTML files via FTP
    - name: Deploy HTML to server
      run: |
        lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{
          secrets.FTP_HOSTNAME }} -e "mirror -R ./public_html /public_html/mda; quit"
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_HOSTNAME: ${{ secrets.FTP_HOSTNAME }}
